const state={token:sessionStorage.getItem('coffee_token')||'',user:null,records:[],users:[],dashboard:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function api(action,payload={}){const r=await fetch('/api/gas',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,token:state.token,...payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||'เกิดข้อผิดพลาด');return d.data;}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast show'+(error?' error':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',3000)}
function fmt(n){return new Intl.NumberFormat('th-TH',{maximumFractionDigits:2}).format(Number(n)||0)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showApp(user){state.user=user;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#sideName').textContent=user.displayName;$('#sideRole').textContent=user.role==='admin'?'ผู้ดูแลระบบ':'เจ้าหน้าที่สำรวจ';$('#avatar').textContent=user.displayName.slice(0,1);$$('.admin-only').forEach(el=>el.classList.toggle('hidden',user.role!=='admin'));navigate('dashboard')}
function logout(){state.token='';state.user=null;sessionStorage.removeItem('coffee_token');$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')}
async function bootstrap(){if(!state.token)return;try{const d=await api('me');showApp(d.user)}catch{logout()}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const f=new FormData(e.target);try{const d=await api('login',{username:f.get('username'),password:f.get('password')});state.token=d.token;sessionStorage.setItem('coffee_token',d.token);showApp(d.user)}catch(err){$('#loginError').textContent=err.message}});
$('#logoutBtn').onclick=async()=>{try{await api('logout')}catch{}logout()};
const pageMeta={dashboard:['ภาพรวมข้อมูลกาแฟ','ข้อมูลต้นน้ำและกลางน้ำจากพื้นที่สำรวจ'],survey:['บันทึกแบบสำรวจ','กรอกข้อมูลพื้นฐาน การผลิต ตลาด และมาตรฐาน'],records:['รายการข้อมูล','ค้นหาและจัดการแบบสำรวจ'],users:['จัดการผู้ใช้','บัญชีเจ้าหน้าที่และสิทธิ์การเข้าถึง']};
async function navigate(name){$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$$('.page').forEach(x=>x.classList.toggle('active',x.id===name+'Page'));$('#pageTitle').textContent=pageMeta[name][0];$('#pageSubtitle').textContent=pageMeta[name][1];try{if(name==='dashboard')await loadDashboard();if(name==='records')await loadRecords();if(name==='users')await loadUsers()}catch(e){toast(e.message,true)}}
$$('nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$('#refreshBtn').onclick=loadDashboard;$('#dashYear').onchange=loadDashboard;$('#dashProvince').onchange=loadDashboard;
async function loadDashboard(){const data=await api('dashboard',{year:$('#dashYear').value,province:$('#dashProvince').value});state.dashboard=data;renderDashboard(data);$('#updatedAt').textContent=new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}
function syncOptions(el,values,label){const val=el.value;el.innerHTML=`<option value="">${label}</option>`+values.map(v=>`<option>${esc(v)}</option>`).join('');el.value=val}
function renderDashboard(d){syncOptions($('#dashYear'),d.filters.years,'ทุกปีข้อมูล');syncOptions($('#dashProvince'),d.filters.provinces,'ทุกจังหวัด');$('#mPlanted').textContent=fmt(d.totals.plantedAreaRai);$('#mHarvested').textContent=fmt(d.totals.harvestedAreaRai);$('#mProduction').textContent=fmt(d.totals.productionKg);$('#mRecords').textContent=fmt(d.totals.records);$('#upstreamCount').textContent=d.stages['ต้นน้ำ']||0;$('#midstreamCount').textContent=d.stages['กลางน้ำ']||0;renderProvince(d.provinces);renderStandards(d.standards,d.totals.records);renderBuyers(d.buyers)}
function renderProvince(rows){const el=$('#provinceChart');if(!rows.length){el.className='bars empty-state';el.textContent='ยังไม่มีข้อมูล';return}el.className='bars';const max=Math.max(...rows.map(x=>Math.max(x.plantedAreaRai,x.productionKg)))||1;el.innerHTML=rows.slice(0,8).map(x=>`<div class="bar-col"><div class="bar-pair"><i title="พื้นที่ ${fmt(x.plantedAreaRai)} ไร่" style="height:${Math.max(3,x.plantedAreaRai/max*100)}%"></i><i title="ผลผลิต ${fmt(x.productionKg)} กก." style="height:${Math.max(3,x.productionKg/max*100)}%"></i></div><small>${esc(x.province)}</small></div>`).join('')}
function renderStandards(rows,total){const el=$('#standardChart');if(!rows.length){el.className='donut-wrap empty-state';el.textContent='ยังไม่มีข้อมูล';return}const colors=['#21583e','#d1a343','#b9633c','#4d7c88','#8d7055','#aab9a9'];let deg=0,parts=[];rows.forEach((x,i)=>{const end=deg+(x.count/total*360);parts.push(`${colors[i%colors.length]} ${deg}deg ${end}deg`);deg=end});el.className='donut-wrap';el.innerHTML=`<div class="donut" style="background:conic-gradient(${parts.join(',')})"></div><div class="legend">${rows.map((x,i)=>`<div><span><i style="background:${colors[i%colors.length]}"></i>${esc(x.name)}</span><b>${x.count}</b></div>`).join('')}</div>`}
function renderBuyers(rows){const el=$('#buyerChart');if(!rows.length){el.className='buyer-list empty-state';el.textContent='ยังไม่มีข้อมูล';return}const max=Math.max(...rows.map(x=>x.productionKg))||1;el.className='buyer-list';el.innerHTML=rows.map(x=>`<div class="buyer-row"><span>${esc(x.name)}</span><div class="buyer-track"><i style="width:${x.productionKg/max*100}%"></i></div><b>${fmt(x.productionKg)} กก.</b></div>`).join('')}
$('#surveyForm').addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));['plantedAreaRai','harvestedAreaRai','productionKg','averagePrice','reportYear'].forEach(k=>f[k]=f[k]===''?'':Number(f[k]));const action=f.id?'updateSurvey':'createSurvey';try{await api(action,{survey:f});toast('บันทึกข้อมูลเรียบร้อย');resetSurvey();navigate('records')}catch(err){toast(err.message,true)}});
function resetSurvey(){const form=$('#surveyForm');form.reset();form.elements.id.value='';form.elements.reportYear.value=new Date().getFullYear()+543;form.querySelector('button[type=submit]').textContent='บันทึกแบบสำรวจ'}$('#resetSurvey').onclick=resetSurvey;
async function loadRecords(){const d=await api('listSurveys');state.records=d.records;renderRecords()}
function renderRecords(){const q=$('#recordSearch').value.toLowerCase();const rows=state.records.filter(x=>[x.respondentName,x.province,x.siteName].join(' ').toLowerCase().includes(q));$('#recordsBody').innerHTML=rows.length?rows.map(x=>`<tr><td><b>${esc(x.respondentName)}</b><br><small>${esc(x.siteName)}</small></td><td>${esc(x.district)}, ${esc(x.province)}</td><td><span class="tag">${esc(x.stage)}</span></td><td>${esc(x.coffeeType)}</td><td>${fmt(x.productionKg)} กก.</td><td>${esc(x.createdByName||x.createdBy)}</td><td><div class="row-actions">${state.user.role==='admin'?`<button class="icon-btn" onclick="editSurvey('${esc(x.id)}')">แก้ไข</button><button class="icon-btn danger" onclick="deleteSurvey('${esc(x.id)}')">ลบ</button>`:''}</div></td></tr>`).join(''):'<tr><td colspan="7" class="empty-state">ยังไม่มีข้อมูล</td></tr>'}
$('#recordSearch').oninput=renderRecords;
window.editSurvey=id=>{const x=state.records.find(r=>r.id===id);if(!x)return;const form=$('#surveyForm');Object.entries(x).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v});form.querySelector('button[type=submit]').textContent='บันทึกการแก้ไข';navigate('survey')};
window.deleteSurvey=async id=>{if(!confirm('ยืนยันการลบแบบสำรวจนี้?'))return;try{await api('deleteSurvey',{id});toast('ลบข้อมูลแล้ว');loadRecords()}catch(e){toast(e.message,true)}};
async function loadUsers(){const d=await api('listUsers');state.users=d.users;$('#usersBody').innerHTML=d.users.map(x=>`<tr><td><b>${esc(x.username)}</b></td><td>${esc(x.displayName)}</td><td><span class="tag">${x.role}</span></td><td>${x.active?'ใช้งาน':'ปิดใช้งาน'}</td><td><button class="icon-btn" onclick="toggleUser('${esc(x.username)}',${!x.active})">${x.active?'ปิด':'เปิด'}ใช้งาน</button></td></tr>`).join('')}
$('#addUserBtn').onclick=()=>{$('#userForm').reset();$('#userDialog').showModal()};$('#closeUserDialog').onclick=()=>$('#userDialog').close();
$('#userForm').addEventListener('submit',async e=>{e.preventDefault();const user=Object.fromEntries(new FormData(e.target));try{await api('createUser',{user});$('#userDialog').close();toast('เพิ่มผู้ใช้แล้ว');loadUsers()}catch(err){toast(err.message,true)}});
window.toggleUser=async(username,active)=>{try{await api('setUserActive',{username,active});toast('ปรับสถานะแล้ว');loadUsers()}catch(e){toast(e.message,true)}};
resetSurvey();bootstrap();setInterval(()=>{if(state.user&&$('#dashboardPage').classList.contains('active'))loadDashboard().catch(()=>{})},15000);
