const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
for(const file of ['index.html','styles.css','map.css','app.js','api/gas.js','apps-script/Code.gs','apps-script/appsscript.json','vercel.json'])assert.ok(fs.existsSync(path.join(root,file)),file+' missing');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const id of ['loginForm','dashboardPage','surveyForm','surveyMap','seedMockBtn','currentLocationBtn','recordsPage','usersPage'])assert.match(html,new RegExp(`id="${id}"`));
assert.match(html,/leaflet@1\.9\.4/);
assert.match(html,/name="latitude"[^>]+required/);
assert.match(html,/name="longitude"[^>]+required/);
const gas=fs.readFileSync(path.join(root,'apps-script/Code.gs'),'utf8');
for(const fn of ['createCoffeeSheet','setupCoffeeSheet','migrateCoffeeSheet','seedMockData','doPost','login_','createSurvey_','updateSurvey_','deleteSurvey_','seedMockSurveys_','dashboard_','createUser_','coordinate_'])assert.match(gas,new RegExp(`function ${fn}\\(`));
assert.match(gas,/updatedAt','latitude','longitude'/);
assert.match(gas,/const MOCK_SURVEYS = \[/);
assert.match(gas,/locations};/);
new vm.Script(gas,{filename:'Code.gs'});
const validSurvey={respondentName:'ตัวอย่าง',respondentType:'เกษตรกร',phone:'',reportYear:2569,province:'เชียงราย',district:'แม่สรวย',subdistrict:'วาวี',siteName:'แปลงตัวอย่าง',stage:'ต้นน้ำ',coffeeType:'อะราบิกา',plantedAreaRai:10,harvestedAreaRai:8,productionKg:3000,productForm:'ผลสด (เชอร์รี)',buyerSource:'สหกรณ์/กลุ่มเกษตรกร',averagePrice:30,productionStandard:'GAP',certificateNo:'',challenges:'',notes:'',latitude:19.8481234,longitude:99.4971234};
const validated=vm.runInNewContext(`${gas};validateSurvey_(${JSON.stringify(validSurvey)})`);
assert.equal(validated.latitude,19.848123);
assert.equal(validated.longitude,99.497123);
assert.throws(()=>vm.runInNewContext(`${gas};coordinate_(91,'Latitude',-90,90)`),/Latitude/);
JSON.parse(fs.readFileSync(path.join(root,'apps-script/appsscript.json'),'utf8'));
JSON.parse(fs.readFileSync(path.join(root,'vercel.json'),'utf8'));
assert.match(fs.readFileSync(path.join(root,'api/gas.js'),'utf8'),/GAS_WEB_APP_URL/);
new vm.Script(fs.readFileSync(path.join(root,'api/gas.js'),'utf8'),{filename:'api/gas.js'});
new vm.Script(fs.readFileSync(path.join(root,'app.js'),'utf8'),{filename:'app.js'});
console.log('Package validation passed: UI, Vercel proxy, Apps Script API, and configuration files are present and syntactically valid.');
